/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

import "sst"
declare module "sst" {
  export interface Resource {
    "API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
// cloudflare 
import * as cloudflare from "@cloudflare/workers-types";
declare module "sst" {
  export interface Resource {
    "AddressValidationDB": cloudflare.D1Database
    "DailyImportHandler": cloudflare.Service
    "Hono": cloudflare.Service
  }
}

import "sst"
export {}